# Generated by Django 6.1 on 2026-08-11 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('waiting_for_reply', 'Waiting for Reply'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('waiting_for_decision', 'Waiting for Decision'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], default='interested', max_length=40)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('interview_completed_at', models.DateField(blank=True, null=True)),
                ('offer_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_16fc9d_idx')],
            },
        ),
    ]
