# Generated by Django 6.1 on 2026-08-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('updated', 'Updated'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('reminder_created', 'Reminder created'), ('reminder_completed', 'Reminder completed')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
