# Generated by Django 6.1 on 2026-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Application deadline'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateField(blank=True, null=True, verbose_name='Applied at'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Interview at'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Interview completed at'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, verbose_name='Job URL'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='offer_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Offer deadline'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('waiting_for_reply', 'Waiting for Reply'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('waiting_for_decision', 'Waiting for Decision'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], default='interested', max_length=40, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
