# Generated by Django 6.1 on 2026-08-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_jobapplication_application_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_status', models.CharField(choices=[('interested', 'Interested'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('waiting_for_reply', 'Waiting for Reply'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('waiting_for_decision', 'Waiting for Decision'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], max_length=40)),
                ('anchor_type', models.CharField(choices=[('application_deadline', 'Application deadline'), ('applied_at', 'Applied at'), ('interview_at', 'Interview at'), ('interview_completed_at', 'Interview completed at'), ('offer_deadline', 'Offer deadline'), ('status_changed_at', 'Status changed at')], max_length=50)),
                ('offset_days', models.PositiveIntegerField(default=0)),
                ('offset_direction', models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=10)),
                ('title_template', models.CharField(help_text='Example: Follow up for {job_title} at {company_name}', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trigger_status', 'anchor_type', 'offset_days'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('rule', 'Generated by rule'), ('manual', 'Manual')], default='rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='applications.jobapplication')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reminders', to='applications.reminderrule')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='application_applica_5ea1cb_idx'), models.Index(fields=['due_at'], name='application_due_at_19121d_idx')],
            },
        ),
    ]
