# Generated by Django 6.1 on 2026-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_reminderrule_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='Job description'),
        ),
    ]
