# Generated by Django 6.1 on 2026-10-08 11:00

from django.db import migrations
from applications.default_reminder_rules import DEFAULT_REMINDER_RULES


def create_default_reminder_rules(apps, schema_editor):
    ReminderRule = apps.get_model("applications", "ReminderRule")

    for rule_data in DEFAULT_REMINDER_RULES:
        ReminderRule.objects.update_or_create(
            name=rule_data["name"],
            trigger_status=rule_data["trigger_status"],
            defaults=rule_data,
        )


def remove_default_reminder_rules(apps, schema_editor):
    ReminderRule = apps.get_model("applications", "ReminderRule")

    rule_names = [
        rule_data["name"]
        for rule_data in DEFAULT_REMINDER_RULES
    ]

    ReminderRule.objects.filter(name__in=rule_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_calendarfeed'),
    ]


    operations = [
        migrations.RunPython(
            create_default_reminder_rules,
            remove_default_reminder_rules,
        ),
    ]