from datetime import datetime, time, timedelta
from django.utils import timezone
from applications.models import ApplicationEvent, JobApplication, Reminder, ReminderRule

"""
Reminder generation logic for job applications.

Evaluates reminder rules, creates concrete reminders, and cancels outdated
rule-based reminders when workflow states change.
"""

def cancel_open_rule_based_reminders(application):
    """
    Cancel all open reminders that were generated by rules for this application.

    This is used when an application changes workflow state. Reminders from the
    previous state may no longer be relevant, so they should not remain active.
    """
    Reminder.objects.filter(
        application=application,
        status=Reminder.Status.OPEN,
        source=Reminder.Source.RULE,
    ).update(
        status=Reminder.Status.CANCELLED
    )

def get_status_changed_at(application):
    """
    Return the timestamp of the latest event where the application entered
    its current status.

    Some reminder rules use the moment of entering a state as their anchor,
    for example "Waiting for Reply + 10 days".
    """
    event = application.events.filter(
        event_type=ApplicationEvent.EventType.STATUS_CHANGED,
        new_status=application.status,
    ).order_by("-created_at").first()

    if event:
        return event.created_at

    return timezone.now()

def date_to_datetime(value):
    """
    Convert a DateField or DateTimeField value into a timezone-aware datetime.

    Date-only fields are interpreted as 09:00 on that date. This gives
    deadline-based reminders a consistent time of day.
    """
    if value is None:
        return None

    if isinstance(value, datetime):
        if timezone.is_naive(value):
            return timezone.make_aware(value)
        return value

    return timezone.make_aware(
        datetime.combine(value, time(hour=9, minute=0))
    )

def resolve_anchor_datetime(application, rule):
    """
    Resolve the datetime anchor for a reminder rule.

    The anchor is the date or timestamp used as the basis for calculating
    the reminder due date.
    """
    if rule.anchor_type == ReminderRule.AnchorType.APPLICATION_DEADLINE:
        return date_to_datetime(application.application_deadline)

    if rule.anchor_type == ReminderRule.AnchorType.APPLIED_AT:
        return date_to_datetime(application.applied_at)

    if rule.anchor_type == ReminderRule.AnchorType.INTERVIEW_AT:
        return date_to_datetime(application.interview_at)

    if rule.anchor_type == ReminderRule.AnchorType.INTERVIEW_COMPLETED_AT:
        return date_to_datetime(application.interview_completed_at)

    if rule.anchor_type == ReminderRule.AnchorType.OFFER_DEADLINE:
        return date_to_datetime(application.offer_deadline)

    if rule.anchor_type == ReminderRule.AnchorType.STATUS_CHANGED_AT:
        return get_status_changed_at(application)

    return None

def apply_offset(anchor, rule):
    """
    Apply the rule offset to the anchor datetime.

    Example:
    - interview_at - 1 day
    - applied_at + 14 days
    """

    delta = timedelta(days=rule.offset_days)

    if rule.offset_direction == ReminderRule.OffsetDirection.BEFORE:
        return anchor - delta

    return anchor + delta

def render_reminder_title(application, rule):
    """
    Render the reminder title from the rule template.

    The template can reference selected application fields.
    """
    return rule.title_template.format(
        job_title=application.job_title,
        company_name=application.company_name,
        status=application.get_status_display(),
    )


def generate_reminders_for_application(application):
    """
    Generate reminders for the application's current workflow state.

    The function:
    1. stops reminder generation for terminal states
    2. finds active rules for the current status
    3. resolves each rule's anchor datetime
    4. applies the offset
    5. prevents duplicate open reminders
    6. creates concrete Reminder records
    """
    if application.status in [
        JobApplication.Status.REJECTED,
        JobApplication.Status.WITHDRAWN,
        JobApplication.Status.ARCHIVED,
    ]:
        cancel_open_rule_based_reminders(application)
        return []

    rules = ReminderRule.objects.filter(
        trigger_status=application.status,
        is_active=True,
    )

    created_reminders = []

    for rule in rules:
        anchor = resolve_anchor_datetime(application, rule)

         # If the required anchor date is missing, the rule cannot be applied.
        if not anchor:
            continue

        due_at = apply_offset(anchor, rule)
        title = render_reminder_title(application, rule)

        # Prevent duplicate open reminders for the same application and rule
        exists = Reminder.objects.filter(
            application=application,
            rule=rule,
            status=Reminder.Status.OPEN,
        ).exists()

        if exists:
            continue

        reminder = Reminder.objects.create(
            application=application,
            rule=rule,
            title=title,
            due_at=due_at,
            source=Reminder.Source.RULE,
        )
        # Record reminder generation in the application history
        ApplicationEvent.objects.create(
            application=application,
            event_type=ApplicationEvent.EventType.REMINDER_CREATED,
            description=f"Reminder created: {title}"
        )

        created_reminders.append(reminder)

    return created_reminders